### ISSUE TITLE
add 3rd party server configuration into the UI

### ISSUE THREAD

**Issue by MagicAndre1981** [rajkumar-rangaraj/PDB-Downloader#1]
Please add an option to add 3rd party symbol servers to the UI. Adding this via config is not user friendly.

**Comment by rajkumar-rangaraj** [comment]
We will have this in our next release. Thanks!

**Comment by MagicAndre1981** [comment]
can you please push the code so that I can build the new version on my own?

**Comment by MagicAndre1981** [comment]
any ETA for the next version?

**Comment by MagicAndre1981** [comment]
open it again or provide the updated version, please!

**Comment by RichardMcKee** [comment]
Bump.

**Comment by MagicAndre1981** [comment]
> Bump.

I doubt that this will be ever fixed.  It don't expect any update from the code owner @rajkumar-rangaraj
